#! /usr/bin/env python
# -*- coding: utf-8 -*-
#
# Touch Portal Controller - Constants © Autolog 2018
#
# plugin Constants

# noinspection PyUnresolvedReferences

try:
    import indigo
except ImportError, e:
    pass

K_LOG_LEVEL_NOT_SET = 0
K_LOG_LEVEL_DETAILED_DEBUGGING = 5
K_LOG_LEVEL_DEBUGGING = 10
K_LOG_LEVEL_INFO = 20
K_LOG_LEVEL_WARNING = 30
K_LOG_LEVEL_ERROR = 40
K_LOG_LEVEL_CRITICAL = 50

K_LOG_LEVEL_TRANSLATION = {}
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_NOT_SET] = "Not Set"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_DETAILED_DEBUGGING] = "Detailed debugging"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_DEBUGGING] = "Debugging"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_INFO] = "Info"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_WARNING] = "Warning"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_ERROR] = "Error"
K_LOG_LEVEL_TRANSLATION[K_LOG_LEVEL_CRITICAL] = "Critical"

TP_DEVICE_TYPEID = "touchPortal"  # See definition in Devices.xml

# Globals dictionary 'index' values
K_ACTIVE = 0
K_ADDRESS = 1
K_API_VERSION = 2
K_AUTO_CONNECT = 3
K_BRIGHTNESS = 4
K_CONSTANT = 5
K_DEBUG = 6
K_DEFAULT_DATE_TIME = 7
K_DESKTOP_USER_DATA_FOLDER_PATH = 8
K_DEVICE_STARTED = 9
K_ENABLED = 10
K_EVENT = 11
K_EVENT_LOG = 12
K_HOST = 13
K_INITIALISED = 14
K_LOCK = 15
K_LOG_TO_EVENT_LOG = 16
K_LOG_TO_PLUGIN_LOG = 17
K_METHOD_TRACE = 18
K_MONITORED_DEVICES = 19
K_ON_OFF = 20
K_PATH = 21
K_PLUGIN_DISPLAY_NAME = 22
K_PLUGIN_ID = 23
K_PLUGIN_INFO = 24
K_PLUGIN_VERSION = 25
K_PORT = 26
K_PREVIOUS_LOGGING = 27
K_PREVIOUS_METHOD_TRACE = 28
K_PREVIOUS_TP_HANDLER = 29
K_QUEUES = 30
K_RECOVERY_INVOKED = 31
K_RGB = 32
K_RECEIVE_FROM_SEND_TO_TP = 33
K_SHOW_MESSAGES = 34
K_SHOW_VARIABLE_VALUE = 35
K_SOCKETS = 36
K_SOCKET_RETRY_SECONDS = 37
K_SOCKET_RETRY_SILENT_AFTER = 38
K_THREAD = 39
K_THREADS = 40
K_TIMEOUT = 41
K_TP = 42
K_TP_DEVICES = 43
K_TP_DEVICE_INDIGO_ACTION_ID = 44
K_TP_DEVICE_INDIGO_DEVICE_DIM_ACTION = 45
K_TP_DEVICE_INDIGO_DEVICE_ID = 46
K_TP_DEVICE_INDIGO_DEVICE_NAME = 47
K_TP_DEVICE_INDIGO_DEVICE_SUPPORTS_ON_OFF = 48
K_TP_DEVICE_INDIGO_DEVICE_SUPPORTS_RGB = 49
K_TP_DEVICE_INDIGO_VARIABLE_ID = 50
K_TP_DEVICE_MODE = 51
K_TP_DEVICE_NAME = 52
K_TP_PLUGIN_INFO = 53
K_TP_PLUGIN_VERSION = 54
K_TP_SOCKET = 55
K_MONITORED_VARIABLES = 56
K_TP_USER_DATA_FOLDER_PATH = 57

K_THREAD_READER = 56
K_THREAD_HANDLER = 57
K_INITIAL_DEVICE_CONFIG_VALUES = 58

TP_MONITOR_TP_DESKTOP_DEV_ID = 0
TP_MONITOR_TP_STATE_ID = 1
TP_MONITOR_ON_OFF = 2
TP_MONITOR_BRIGHTNESS = 3
TP_MONITOR_RGB = 4
TP_MONITOR_TEXT = 3
TP_MONITOR_TRUE_FALSE = 2

# Device Configuration Defaults
TP_AUTO_CONNECT_DEFAULT = True
TP_SHOW_MESSAGES_DEFAULT = False
TP_HOST_DEFAULT = "127.0.0.1"
TP_PORT_DEFAULT = "12136"
TP_DESKTOP_PLUGIN_LOCATION = "plugins/indigo Domotics"
TP_DESKTOP_USER_DATA_FOLDER_DEFAULT_PATH = "/Documents/TouchPortal"
TP_DESKTOP_PLUGIN_ICON_FILENAME = "indigo_icon.png"
TP_SHOW_VARIABLE_VALUE_DEFAULT = True
TP_SOCKET_RETRY_DEFAULT = "15"
TP_SOCKET_RETRY_SILENT_AFTER_DEFAULT = "10"
TP_SOCKET_TIMEOUT_DEFAULT = 3
TP_RESOURCES_ICON_PATH_FILENAME = "Plugins/TouchPortal.indigoPlugin/Contents/Resources/Indigo Domotics/indigo_icon.png"
TP_DESKTOP_VALIDITY_CHECK_FOLDER = "iconpacks"

# Touch Portal commands from entry.tp
TP_ENTRY_COMMAND_DEVICE_TURN_ON = "indigo_device_turn_on"
TP_ENTRY_COMMAND_DEVICE_TURN_OFF = "indigo_device_turn_off"
TP_ENTRY_COMMAND_DEVICE_TOGGLE = "indigo_device_toggle"
TP_ENTRY_COMMAND_DEVICE_BRIGHTNESS_SET = "indigo_device_brightness_set"
TP_ENTRY_COMMAND_DEVICE_BRIGHTEN = "indigo_device_brighten"
TP_ENTRY_COMMAND_DEVICE_DIM = "indigo_device_dim"
TP_ENTRY_COMMAND_DEVICE_SET_COLOUR = "indigo_device_colour_set"
TP_ENTRY_COMMANDS_DEVICE = (TP_ENTRY_COMMAND_DEVICE_TURN_ON, TP_ENTRY_COMMAND_DEVICE_TURN_OFF, TP_ENTRY_COMMAND_DEVICE_TOGGLE, TP_ENTRY_COMMAND_DEVICE_BRIGHTNESS_SET,
                            TP_ENTRY_COMMAND_DEVICE_BRIGHTEN, TP_ENTRY_COMMAND_DEVICE_DIM, TP_ENTRY_COMMAND_DEVICE_SET_COLOUR)

TP_ENTRY_COMMAND_ACTION_GROUP_RUN = "indigo_action_group_run"
TP_ENTRY_COMMANDS_ACTION_GROUP = (TP_ENTRY_COMMAND_ACTION_GROUP_RUN,)  # May have more Action Group commands added in the future

TP_ENTRY_COMMAND_VARIABLE_SET_TEXT = "indigo_variable_set_text"
TP_ENTRY_COMMAND_VARIABLE_SET_TRUE = "indigo_variable_set_true"
TP_ENTRY_COMMAND_VARIABLE_SET_FALSE = "indigo_variable_set_false"
TP_ENTRY_COMMAND_VARIABLE_TOGGLE = "indigo_variable_toggle"

TP_ENTRY_COMMANDS_VARIABLE = (TP_ENTRY_COMMAND_VARIABLE_SET_TEXT, TP_ENTRY_COMMAND_VARIABLE_SET_TRUE, TP_ENTRY_COMMAND_VARIABLE_SET_FALSE, TP_ENTRY_COMMAND_VARIABLE_TOGGLE)

# Touch Portal commands from entry.tp (translation)
TP_ENTRY_TRANSLATION = {}
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_DEVICE_TURN_ON] = "Device Turn On"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_DEVICE_TURN_OFF] = "Device Turn Off"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_DEVICE_TOGGLE] = "Device Toggle"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_DEVICE_BRIGHTNESS_SET] = "Device Brightness Set"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_DEVICE_BRIGHTEN] = "Device Brighten"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_DEVICE_SET_COLOUR] = "Device Colour Set"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_DEVICE_DIM] = "Device Dim"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_ACTION_GROUP_RUN] = "Action Group Run"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_VARIABLE_SET_TEXT] = "Variable Set Text"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_VARIABLE_SET_TRUE] = "Variable Set True"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_VARIABLE_SET_FALSE] = "Variable Set false"
TP_ENTRY_TRANSLATION[TP_ENTRY_COMMAND_VARIABLE_TOGGLE] = "Variable Toggle"

# Plugin Internal command(s)
CMD_PROCESS_RECEIVED_TP_MESSAGE = 0
CMD_PROCESS_SEND_TP_MESSAGE = 1
CMD_PROCESS_REFRESH_TP_PLUGIN_STATES = 2

# Plugin Internal command(s) (translation)
CMD_TRANSLATION = {}
CMD_TRANSLATION[CMD_PROCESS_RECEIVED_TP_MESSAGE] = "PROCESS RECEIVED MESSAGE FROM TOUCH PORTAL"
CMD_TRANSLATION[CMD_PROCESS_SEND_TP_MESSAGE] = "PROCESS SEND MESSAGE TO TOUCH PORTAL"
CMD_TRANSLATION[CMD_PROCESS_REFRESH_TP_PLUGIN_STATES] = "PROCESS REFRESH TP PLUGIN STATES"

# QUEUE Priorities
QUEUE_PRIORITY_HIGH   = 100
QUEUE_PRIORITY_MEDIUM = 200
QUEUE_PRIORITY_LOW    = 400
